/* SPDX-License-Identifier: GPL-2.0-or-later */
/*
 * Copyright (C) 2023 bmax121. All Rights Reserved.
 */

#ifndef _ETHEREAL_UAPI_SCDEFS_H_
#define _ETHEREAL_UAPI_SCDEFS_H_

#define SUPERCALL_HELLO 0x1000
#define SUPERCALL_SU 0x1010

#define SUPERCALL_KSTORAGE_WRITE 0x1041
#define SUPERCALL_KSTORAGE_READ 0x1042
#define SUPERCALL_KSTORAGE_REMOVE 0x1044
#define SUPERCALL_CONTROL_FEATURE 0x1046

#define SUPERCALL_SU_GRANT_UID 0x1100
#define SUPERCALL_SU_REVOKE_UID 0x1101
#define SUPERCALL_SU_NUMS 0x1102
#define SUPERCALL_SU_LIST 0x1103
#define SUPERCALL_SU_PROFILE 0x1104
#define SUPERCALL_SU_GET_PATH 0x1110
#define SUPERCALL_SU_RESET_PATH 0x1111

#define SUPERCALL_HELLO_MAGIC 0x11581158u
#define SUPERCALL_SCONTEXT_LEN 0x60
#define KSTORAGE_EXCLUDE_LIST_GROUP 1
#define SU_PATH_MAX_LEN 128

struct su_profile {
    uid_t uid;
    uid_t to_uid;
    char scontext[SUPERCALL_SCONTEXT_LEN];
};

#endif
